### ISSUE TITLE
plural-cli can't be setup from a GitHub action starting from 

### ISSUE THREAD

**Issue by NicolasGuary** [pluralsh/plural-cli#413]
## Summary

Trying to run a GitHub action workflow to deploy to Plural.
I'm using the following block in my action : 
```
    - name: Login to Plural
      uses: pluralsh/setup-plural@v0.1.5
      with:
        config: ${{ secrets.PLURAL_CONFIG }}
        vsn: 0.6.19
```

Everything works fine if I don't specify `vsn` which defaults to `v0.5.18 `or if I set `vsn` to `0.6.18`

But starting from 0.6.19, setup-plural fails with the following error : 
```
/usr/bin/chmod +x /opt/hostedtoolcache/plural/0.6.19/x64/plural
installed plural
wrote config file
/opt/hostedtoolcache/plural/0.6.19/x64/plural --help
/opt/hostedtoolcache/plural/0.6.19/x64/plural: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
Error: The process '/opt/hostedtoolcache/plural/0.6.19/x64/plural' failed with exit code 1[27](https://github.com/beamysoftware/data-pipelines/actions/runs/5143998884/jobs/9259723647#step:7:28)
```

I believe a dependency might be missing.

## Reproduction

Run the following GitHub action : 

```
name: Plural CLI fail 

on:
  push:
    branches:
      - "<your_test_branch>"

jobs:
  failing_job:
    environment:
      name: <your_env>
      url: <url>
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v3

    - name: Login to Plural
      uses: pluralsh/setup-plural@v0.1.5
      with:
        config: ${{ secrets.PLURAL_CONFIG }}
        vsn: 0.6.19
```

If `vsn` is `0.6.19` or above it will fail with the error described above : 
```
/opt/hostedtoolcache/plural/0.6.19/x64/plural: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
```
---
#### Message from the maintainers:
Impacted by this bug? Give it a 👍. We factor engagement into prioritization.
